use std::collections::BTreeMap;
use std::fs;
use std::io::{self, Write};
use std::path::Path;

use clap::Parser;
use clap_mangen::Man;
use clap_mangen::roff::{Roff, bold, roman};

#[derive(Parser)]
#[command(about = "Generate the checked-in tk(1) reference")]
struct Args {
    /// Fail if man/tk.1 is stale, without writing files.
    #[arg(long)]
    check: bool,
}

fn main() -> io::Result<()> {
    let args = Args::parse();
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../man");
    let mut guidance = BTreeMap::new();
    for entry in fs::read_dir(root.join("commands"))? {
        let path = entry?.path();
        if path.extension().is_some_and(|ext| ext == "roff") {
            let name = path.file_stem().unwrap().to_string_lossy();
            guidance.insert(format!("tk-{name}"), fs::read_to_string(path)?);
        }
    }
    let page = render(
        tk::cli::command(),
        guidance,
        &fs::read_to_string(root.join("sections/description.roff"))?,
        &fs::read_to_string(root.join("sections/reference.roff"))?,
    )?;
    let path = root.join("tk.1");
    if args.check {
        if fs::read(&path)? != page {
            return Err(io::Error::other("man/tk.1 is stale; run make manpage"));
        }
    } else {
        fs::write(path, page)?;
    }
    Ok(())
}

fn render(
    mut command: clap::Command,
    mut guidance: BTreeMap<String, String>,
    description: &str,
    reference: &str,
) -> io::Result<Vec<u8>> {
    command.build();
    let mut page = Vec::new();
    writeln!(
        page,
        ".\\\" Generated by make manpage; edit clap help and man/**/*.roff."
    )?;
    writeln!(page, r#".TH TK 1 "" "" "tk Manual""#)?;
    let man = Man::new(command.clone());
    man.render_name_section(&mut page)?;
    writeln!(page, ".SH SYNOPSIS")?;
    synopsis(&mut page, &mut command)?;
    page.extend_from_slice(description.as_bytes());
    man.render_options_section(&mut page)?;
    writeln!(page, ".SH COMMANDS")?;
    for sub in command.get_subcommands().filter(|sub| !sub.is_hide_set()) {
        render_command(&mut page, sub.clone(), "tk", &mut guidance)?;
    }
    if !guidance.is_empty() {
        return Err(io::Error::other(format!(
            "manual guidance has no public command: {}",
            guidance.keys().cloned().collect::<Vec<_>>().join(", ")
        )));
    }
    page.extend_from_slice(reference.as_bytes());
    Ok(page)
}

fn render_command(
    page: &mut Vec<u8>,
    mut command: clap::Command,
    parent: &str,
    guidance: &mut BTreeMap<String, String>,
) -> io::Result<()> {
    let name = format!("{parent} {}", command.get_name());
    command = command.bin_name(&name);
    let mut heading = Roff::default();
    heading.control("SS", [name.as_str()]);
    heading.to_writer(page)?;
    synopsis(page, &mut command)?;
    let man = Man::new(command.clone());
    sections(page, |out| man.render_description_section(out))?;
    sections(page, |out| man.render_options_section(out))?;
    if let Some(text) = guidance.remove(&name.replace(' ', "-")) {
        writeln!(page, ".PP")?;
        page.extend_from_slice(text.as_bytes());
    }
    for sub in command.get_subcommands().filter(|sub| !sub.is_hide_set()) {
        render_command(page, sub.clone(), &name, guidance)?;
    }
    Ok(())
}

fn synopsis(page: &mut Vec<u8>, command: &mut clap::Command) -> io::Result<()> {
    // clap's usage preserves argument groups and subcommand alternatives.
    let usage = command.render_usage().to_string();
    let mut roff = Roff::default();
    roff.control("nf", []);
    for line in usage.lines() {
        roff.text([roman(line.strip_prefix("Usage: ").unwrap_or(line))]);
    }
    roff.control("fi", []);
    roff.to_writer(page)
}

fn sections(
    page: &mut Vec<u8>,
    render: impl FnOnce(&mut dyn Write) -> io::Result<()>,
) -> io::Result<()> {
    let mut section = Vec::new();
    render(&mut section)?;
    // Keep generated sections below the command heading in the single page.
    for line in String::from_utf8(section)
        .expect("roff writes UTF-8")
        .lines()
    {
        if let Some(title) = line.strip_prefix(".SH ") {
            let mut heading = Roff::default();
            heading.control("PP", []);
            if title != "DESCRIPTION" {
                heading.text([bold(if title == "OPTIONS" {
                    "Arguments and options"
                } else {
                    title.trim_matches('"')
                })]);
            }
            heading.to_writer(page)?;
        } else {
            writeln!(page, "{line}")?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::{Arg, ArgAction, Command};

    #[test]
    fn composes_nested_reference_with_guidance_and_hides_private_commands() {
        let command = Command::new("tk").disable_help_subcommand(true).subcommand(
            Command::new("ship")
                .about("Ship a parcel")
                .arg(
                    Arg::new("destination")
                        .required(true)
                        .help("Delivery address"),
                )
                .arg(
                    Arg::new("copies")
                        .long("copies")
                        .default_value("2")
                        .help("Copies to send"),
                )
                .subcommand(
                    Command::new("confirm").arg(
                        Arg::new("receipt")
                            .long("receipt")
                            .action(ArgAction::SetTrue)
                            .help("Print the receipt"),
                    ),
                )
                .subcommand(Command::new("internal").hide(true)),
        );
        let guidance = BTreeMap::from([
            ("tk-ship".into(), "Parcels cannot be recalled.\n".into()),
            ("tk-ship-confirm".into(), "Keep the receipt.\n".into()),
        ]);
        let page = String::from_utf8(render(command, guidance, "", "").unwrap())
            .unwrap()
            .replace("\\-", "-");

        assert!(page.contains("tk ship [OPTIONS] <destination>"));
        assert!(page.contains("Delivery address"));
        assert!(page.contains("--copies"));
        assert!(page.contains("[default: 2]"));
        let parent_guidance = page.find("Parcels cannot be recalled.").unwrap();
        let child_heading = page.find(".SS \"tk ship confirm\"").unwrap();
        assert!(parent_guidance < child_heading);
        let child = &page[child_heading..];
        assert!(child.contains("--receipt"));
        assert!(child.contains("Print the receipt"));
        assert!(child.contains("Keep the receipt."));
        assert!(!page.contains("internal"));
        assert!(!page.contains("tk-ship(1)"));
    }

    #[test]
    fn refuses_to_drop_guidance_after_a_command_is_removed() {
        let guidance = BTreeMap::from([("tk-removed".into(), "Retained advice.\n".into())]);
        let error = render(Command::new("tk"), guidance, "", "").unwrap_err();
        assert!(error.to_string().contains("tk-removed"));
    }
}
