//! `tk manpage` — print or install the embedded `tk(1)` manpage.
//!
//! Writes the embedded bytes to stdout or, with `--install`, to
//! `<prefix>/share/man/man1/tk.1`. The prefix is the parent of the
//! executable's directory. Installation stages the file before renaming
//! it over the target, preserving an existing manual on failure.

use std::path::Path;

use clap::Args as ClapArgs;

use crate::cli::{CommandError, Deps, Exit};
use crate::commands::staging;
use crate::platform;

/// Generated by `make manpage` and checked in for review before release.
const MANPAGE_BYTES: &[u8] = include_bytes!("../../../../man/tk.1");

/// Stage beside tk.1 so the rename stays on the same filesystem.
const STAGE_NAME_PREFIX: &str = ".tk.1.tmp.";

#[derive(Debug, ClapArgs)]
pub struct Args {
    /// Install the manpage next to the running tk binary.
    #[arg(long)]
    pub install: bool,
}

pub fn run(deps: &mut Deps<'_>, args: Args) -> Result<Exit, CommandError> {
    debug_assert!(
        !MANPAGE_BYTES.contains(&b'\r'),
        "tk.1 must use LF line endings (no CR bytes)"
    );

    if args.install {
        return install(deps);
    }
    let _ = deps.stdout.write_all(MANPAGE_BYTES);
    Ok(Exit::Ok)
}

fn install(deps: &mut Deps<'_>) -> Result<Exit, CommandError> {
    if platform::IS_WINDOWS {
        // Informational success, not a diagnostic: written straight to stderr
        // on the Ok path, so it keeps its own `tk manpage:` prefix (the seam
        // frames only Err).
        let _ = writeln!(deps.stderr, "tk manpage: skipping install on Windows");
        return Ok(Exit::Ok);
    }

    let exe_path = std::env::current_exe().map_err(|err| {
        CommandError::failure(format!(
            "install failed: cannot resolve executable path: {err}"
        ))
    })?;
    let Some(exe_dir) = exe_path.parent() else {
        return Err(CommandError::failure(
            "install failed: cannot resolve executable path: executable path has no parent directory",
        ));
    };

    // Use the parent path so the printed install path contains no `..`.
    let install_prefix = exe_dir.parent().unwrap_or(exe_dir);
    let target_dir = install_prefix.join("share").join("man").join("man1");
    let target_path = target_dir.join("tk.1");

    if let Err(err) = std::fs::create_dir_all(&target_dir) {
        return Err(install_failure(&target_path, &err.to_string()));
    }

    let stage_name = staging::staged_file_name(STAGE_NAME_PREFIX, deps.rng);
    let stage_path = target_dir.join(&stage_name);

    if let Err(err) = std::fs::write(&stage_path, MANPAGE_BYTES) {
        let _ = std::fs::remove_file(&stage_path);
        return Err(install_failure(&target_path, &err.to_string()));
    }

    if let Err(err) = std::fs::rename(&stage_path, &target_path) {
        let _ = std::fs::remove_file(&stage_path);
        return Err(install_failure(&target_path, &err.to_string()));
    }

    let _ = writeln!(
        deps.stdout,
        "Installed manpage at {}",
        target_path.display()
    );
    Ok(Exit::Ok)
}

fn install_failure(path: &Path, reason: &str) -> CommandError {
    CommandError::failure(format!(
        "install failed at {}: {reason}; existing file (if any) left unchanged",
        path.display()
    ))
}
