//! Shared command-output helpers.

const std = @import("std");
const sanitize = @import("../render/sanitize.zig");

/// Write a command success line whose prefix and Display ID are generated by
/// tk, while the Repository Store title may be user/Remote-controlled text.
/// The title is routed through the terminal sanitizer before the trailing
/// newline is emitted.
pub fn writeItemTitleLine(stdout: *std.Io.Writer, prefix: []const u8, display_id: []const u8, title: []const u8) !void {
    try stdout.print("{s}{s} - ", .{ prefix, display_id });
    try sanitize.writeSanitizedLine(stdout, title);
    try stdout.writeAll("\n");
}
